package com.example.hotel.models;

public enum Permiso {
    CREAR_RESERVACION,
    VER_RESERVACIONES,
    VER_RESERVACIONES_CANCELADAS,
    MODIFICAR_RESERVACION,
    CANCELAR_RESERVACION,
    GESTIONAR_HABITACIONES,
    GESTIONAR_CATALOGOS,
    VER_AUDITORIA;
}
